version: '3.5'
services:
  app:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - db
    container_name: roran
    command: python3 bot.py

  database:
    image: postgres:13
    restart: always
    env_file:
      - .database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - db
    container_name: db
volumes:
  database-data:

networks: 
  db: